#!/bin/sh

bulkhead_lm_toolchain_root_dir() {
  if [ -n "${ROOT_DIR:-}" ]; then
    printf '%s\n' "$ROOT_DIR"
  elif [ -n "${BULKHEAD_LM_REMOTE_ROOT_DIR:-}" ]; then
    printf '%s\n' "$BULKHEAD_LM_REMOTE_ROOT_DIR"
  else
    CDPATH= cd -- "$(dirname -- "$0")/.." && pwd
  fi
}

bulkhead_lm_unset_opam_env() {
  unset OPAMSWITCH
  unset OPAM_SWITCH_PREFIX
  unset OPAM_LAST_ENV
  unset CAML_LD_LIBRARY_PATH
  unset OCAML_TOPLEVEL_PATH
  unset OCAMLTOP_INCLUDE_PATH
}

BULKHEAD_LM_TOOLCHAIN_ROOT_DIR=${BULKHEAD_LM_TOOLCHAIN_ROOT_DIR:-$(bulkhead_lm_toolchain_root_dir)}
BULKHEAD_LM_LOCAL_TOOLCHAIN_DIR=${BULKHEAD_LM_LOCAL_TOOLCHAIN_DIR:-$BULKHEAD_LM_TOOLCHAIN_ROOT_DIR/.bulkhead-tools}
BULKHEAD_LM_LOCAL_BIN_DIR=${BULKHEAD_LM_LOCAL_BIN_DIR:-$BULKHEAD_LM_LOCAL_TOOLCHAIN_DIR/bin}
BULKHEAD_LM_LOCAL_INCLUDE_DIR=${BULKHEAD_LM_LOCAL_TOOLCHAIN_DIR:-$BULKHEAD_LM_TOOLCHAIN_ROOT_DIR/.bulkhead-tools}/include
BULKHEAD_LM_LOCAL_LIB_DIR=${BULKHEAD_LM_LOCAL_LIB_DIR:-$BULKHEAD_LM_LOCAL_TOOLCHAIN_DIR/lib}
BULKHEAD_LM_LOCAL_PKGCONFIG_DIR=${BULKHEAD_LM_LOCAL_PKGCONFIG_DIR:-$BULKHEAD_LM_LOCAL_LIB_DIR/pkgconfig}
BULKHEAD_LM_LOCAL_OPAM_BIN=${BULKHEAD_LM_LOCAL_OPAM_BIN:-$BULKHEAD_LM_LOCAL_BIN_DIR/opam}
BULKHEAD_LM_LOCAL_OPAM_ROOT=${BULKHEAD_LM_LOCAL_OPAM_ROOT:-$BULKHEAD_LM_TOOLCHAIN_ROOT_DIR/.opam-root}
BULKHEAD_LM_LOCAL_SWITCH=${BULKHEAD_LM_LOCAL_SWITCH:-$BULKHEAD_LM_TOOLCHAIN_ROOT_DIR}
BULKHEAD_LM_LOCAL_SWITCH_DIR=${BULKHEAD_LM_LOCAL_SWITCH_DIR:-$BULKHEAD_LM_TOOLCHAIN_ROOT_DIR/_opam}
BULKHEAD_LM_LOCAL_OCAML_COMPILER=${BULKHEAD_LM_LOCAL_OCAML_COMPILER:-${BULKHEAD_LM_OCAML_COMPILER:-ocaml-base-compiler.5.2.1}}
BULKHEAD_LM_LOCAL_OPAM_VERSION=${BULKHEAD_LM_LOCAL_OPAM_VERSION:-2.5.0}
BULKHEAD_LM_LOCAL_PKGCONF_VERSION=${BULKHEAD_LM_LOCAL_PKGCONF_VERSION:-2.5.1}
BULKHEAD_LM_LOCAL_PKG_CONFIG_BIN=${BULKHEAD_LM_LOCAL_PKG_CONFIG_BIN:-$BULKHEAD_LM_LOCAL_BIN_DIR/pkg-config}
BULKHEAD_LM_LOCAL_GMP_VERSION=${BULKHEAD_LM_LOCAL_GMP_VERSION:-6.3.0}
BULKHEAD_LM_LOCAL_BOOTSTRAP_LOCK_DIR=${BULKHEAD_LM_LOCAL_BOOTSTRAP_LOCK_DIR:-$BULKHEAD_LM_LOCAL_TOOLCHAIN_DIR/bootstrap.lock}
BULKHEAD_LM_LOCAL_BOOTSTRAP_LOCK_WAIT_SECONDS=${BULKHEAD_LM_LOCAL_BOOTSTRAP_LOCK_WAIT_SECONDS:-1}
BULKHEAD_LM_PACKAGE_NAME=${BULKHEAD_LM_PACKAGE_NAME:-bulkhead_lm}
